services:
  postgres:
    container_name: training_tracker
    image: postgres:16.4
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      PGDATA: data/postgres
    volumes:
    - ./_postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
volumes:
  redis_data: