// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Approach struct {
	ID         string `json:"id"`
	ExerciseID string `json:"exercise_id"`
	Repetition int32  `json:"repetition"`
	Weight     int32  `json:"weight"`
}

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type CreateExercise struct {
	Title         string `json:"title"`
	MuscleGroup   int32  `json:"muscle_group"`
	ApproachCount int32  `json:"approach_count"`
	Weight        int32  `json:"weight"`
	TrainingID    string `json:"training_id"`
}

type CreateExerciseForList struct {
	Title          string `json:"title"`
	CategoryMuscle int32  `json:"category_muscle"`
}

type CreateTraining struct {
	Title    string `json:"title"`
	Duration string `json:"duration"`
	Date     string `json:"date"`
	Notes    string `json:"notes"`
	Type     int32  `json:"type"`
}

type Exercise struct {
	ID           string        `json:"id"`
	TrainingID   string        `json:"training_id"`
	ExerciseList *ExerciseList `json:"exercise_list"`
	Approaches   []*Approach   `json:"approaches"`
}

type ExerciseList struct {
	ID             string     `json:"id"`
	Title          string     `json:"title"`
	CategoryMuscle int32      `json:"category_muscle"`
	CreatedAt      *time.Time `json:"created_at,omitempty"`
}

type GetExerciseList struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"Offset"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Email    string `json:"email"`
	Login    string `json:"login"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

type SearchExercise struct {
	Title         *string `json:"title,omitempty"`
	MuscleGroup   *int32  `json:"muscle_group,omitempty"`
	ApproachCount *int32  `json:"approach_count,omitempty"`
	Weight        *int32  `json:"weight,omitempty"`
	Limit         int32   `json:"limit"`
	Offset        int32   `json:"offset"`
}

type SearchTrainings struct {
	Name   *string `json:"name,omitempty"`
	Type   *int32  `json:"type,omitempty"`
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
}

type Training struct {
	ID        string      `json:"id"`
	UserID    string      `json:"user_id"`
	Title     string      `json:"title"`
	Duration  string      `json:"duration"`
	Date      string      `json:"date"`
	Notes     *string     `json:"notes,omitempty"`
	Exercises []*Exercise `json:"exercises"`
	User      *User       `json:"user,omitempty"`
	CreatedAt *time.Time  `json:"created_at,omitempty"`
}

type User struct {
	ID         string     `json:"id"`
	Email      string     `json:"email"`
	Login      string     `json:"login"`
	Password   string     `json:"password"`
	Role       string     `json:"role"`
	TelegramID *string    `json:"telegram_id,omitempty"`
	CreatedAt  *time.Time `json:"created_at,omitempty"`
}
