// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID         string     `json:"id"`
	Email      string     `json:"email"`
	Login      string     `json:"login"`
	Password   string     `json:"password"`
	Role       string     `json:"role"`
	TelegramID *string    `json:"telegram_id,omitempty"`
	CreatedAt  *time.Time `json:"created_at,omitempty"`
}
